# Generated by Django 6.0.1 on 2026-01-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bloodrequest_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='assigned_bag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_assignment', to='core.bloodinventory'),
        ),
    ]
