# Generated by Django 6.0.1 on 2026-01-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bloodrequest_assigned_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.donor'),
        ),
    ]
